# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20171015_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_questions_scale',
            field=models.TextField(blank=True, help_text="The scale field is only used\nif the question type is 'scale', provide a comma-separated list of\noptions for this question .", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text (multiple line)'), ('short-text', 'short text (one line)'), ('radio', 'radio'), ('select', 'select'), ('select-multiple', 'Select Multiple'), ('select_image', 'Select Image'), (('integer',), 'integer'), ('scale', 'scale')], default='text', max_length=200),
        ),
    ]
