# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applicant',
            field=models.ManyToManyField(related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
