# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170912_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.Team'),
        ),
    ]
