# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-18 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_question_quest_numb'),
        ('website', '0003_project_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ManyToManyField(related_name='website_demoproject_related', to=settings.AUTH_USER_MODEL)),
                ('candidat_answers', models.ManyToManyField(to='survey.Response')),
                ('project_hr_admin', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='applicant',
            field=models.ManyToManyField(related_name='website_project_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
