# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180320_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoproject',
            name='applicant',
            field=models.ManyToManyField(blank=True, related_name='website_demoproject_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demoproject',
            name='candidat_answers',
            field=models.ManyToManyField(blank=True, to='survey.Response'),
        ),
        migrations.AlterField(
            model_name='project',
            name='applicant',
            field=models.ManyToManyField(blank=True, related_name='website_project_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='candidat_answers',
            field=models.ManyToManyField(blank=True, to='survey.Response'),
        ),
    ]
