# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170912_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
