# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180228_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
