# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quest_numb',
            field=models.IntegerField(default=0),
        ),
    ]
