# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20171109_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='multiple_questions_scale',
            field=models.TextField(blank=True, help_text="The scale field is only used\nif the question type is 'scale', provide a comma-separated list of\noptions for this question .", max_length=5000, null=True),
        ),
    ]
